version: 2.1

orbs:
    codecov: codecov/codecov@3.2.5

jobs:
    build:
        docker:
            -   image: cimg/php:8.2
        steps:
            -   checkout
            -   run: sudo apt update
            -   restore_cache:
                    keys:
                        - v1-dependencies-{{ checksum "composer.lock" }}
                        - v1-dependencies-
            -   run: composer install -n --prefer-dist
            -   save_cache:
                    key: v1-dependencies-{{ checksum "composer.lock" }}
                    paths:
                        - ./vendor
            -   run: ./bin/phpunit
            -   run: ./bin/phpunit --coverage-clover coverage/clover/clover.xml --coverage-html coverage/html
            -   codecov/upload
